name: Update Notebooks And Refresh Page
true:
  schedule:
  - cron: 59 4 * * *
jobs:
  update-data:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
    - env:
        actor: ${{ github.actor }}
        event_name: ${{ github.event_name }}
        title: ${{ github.event.issue.title }}
      name: See event name
      run: 'echo "title ${title}"

        echo "actor ${actor}"

        echo "event_name ${event_name}"

        '
    - name: Copy Repository Contents
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: install dependencies
      run: 'sudo apt-get update -y

        sudo apt-get -y --force-yes install chromium-chromedriver

        npm install -g electron@6.1.4 orca

        pip3 install matplotlib pandas numpy scipy seaborn papermill ipykernel jupyter
        folium plotly plotnine psutil pymc3 arviz xlrd altair altair_saver jinja2
        selenium

        python3 -m ipykernel install --user --name python3

        sudo chmod -R 777 .

        '
    - id: update_nb
      name: update notebooks
      run: './_action_files/run_notebooks.sh

        '
    - name: save notebooks images
      run: "git config --global user.email \"github-actions[bot]@users.noreply.github.com\"\
        \ngit config --global user.name \"github-actions[bot]\"\ngit add images/\n\
        git add _notebooks/scripts/\ngit add _notebooks/Market-News.ipynb\ngit add\
        \ _notebooks/App-autocorrelation.ipynb\ngit add _notebooks/App-covid-19.ipynb\
        \        \ngit add _notebooks/App-Correlation_charts.ipynb\ngit add _notebooks/App-markets.ipynb\n\
        git add _notebooks/App-Price_history_charts.ipynb\ngit add _notebooks/App-Scatter_charts.ipynb\n\
        git commit -m '[bot] refresh data' \ngit push -f \n"
    - name: convert notebooks and word docs to posts
      uses: ./_action_files
    - name: setup directories for Jekyll build
      run: 'rm -rf _site

        sudo chmod -R 777 .

        '
    - env:
        JEKYLL_ENV: production
      name: Jekyll build
      uses: docker://hamelsmu/fastpages-jekyll
      with:
        args: bash -c "gem install bundler && jekyll build -V"
    - name: copy CNAME file into _site if CNAME exists
      run: "sudo chmod -R 777 _site/\ncp CNAME _site/ 2>/dev/null || :\n  \n"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
        force_orphan: true
        publish_dir: ./_site
        user_email: github-actions[bot]@users.noreply.github.com
        user_name: github-actions[bot]
